//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worry_freemanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clockin
    {
        public int Clockinid { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Gotowork { get; set; }
        public Nullable<System.DateTime> Gooffwork { get; set; }
    
        public virtual Stafftable Stafftable { get; set; }
    }
}
