//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worry_freemanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class punishments
    {
        public int EventsID { get; set; }
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> Datatime { get; set; }
        public string Amount { get; set; }
    
        public virtual Stafftable Stafftable { get; set; }
    }
}
