//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worry_freemanagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class notice
    {
        public int id { get; set; }
        [AllowHtml]
        public string name { get; set; }
        [AllowHtml]
        public string Content { get; set; }
        [AllowHtml]
        public System.DateTime datatime { get; set; }
    }
}
