//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worry_freemanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainingform
    {
        public int TrainingID { get; set; }
        public string Nametraining { get; set; }
        public string Personnel { get; set; }
        public string Location { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> Datatime { get; set; }
        public Nullable<System.DateTime> Datatimes { get; set; }
    
        public virtual Trainingform Trainingform1 { get; set; }
        public virtual Trainingform Trainingform2 { get; set; }
    }
}
