//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worry_freemanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wage
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public System.DateTime Month { get; set; }
        public string Basicwage { get; set; }
        public string Overtime { get; set; }
        public string Gongz { get; set; }
        public string Insurance { get; set; }
        public string Real { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual Stafftable Stafftable { get; set; }
    }
}
